create table if not exists users
(
    id    bigint generated by default as identity not null
        constraint users_pk
            primary key,
    name  varchar(255) not null,
    email varchar(255) not null
);

alter table users
    owner to postgres;

create table items
(
    id          bigint generated by default as identity not null
        constraint items_pk
            primary key,
    name        varchar(255)  not null,
    description varchar(2000) not null,
    available   boolean       not null,
    owner_id    integer       not null
        constraint items_users_id_fk
            references users,
    request     integer       not null
);

alter table items
    owner to postgres;